OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Office
    Domain: office.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1